const consoleHeaderStyle = "padding: 5px; background-color: white; color: black; font-weight: bold;";
console.log("%cArithmentic Operators", consoleHeaderStyle);
let x = 5 + 2;
console.log(x);
x = 5 - 2;
console.log(x);
x = 5 * 2;
console.log(x);
x = 5 / 2;
console.log(x);
x = 5 % 2;
console.log(x);
x = "Helloooooo" + " " + "You";
console.log(x);
x = 5 ** 3;
console.log(x);
x++;
console.log(x);
x--;
console.log(x);

console.log("%cAssignment Operators", consoleHeaderStyle);
x += 3;
console.log(x);
x %= 3;
console.log(x);
x **= 3;
console.log(x);

console.log("%cComparison Operators", consoleHeaderStyle);
x = 2 == 2;
console.log(x);
x = 2 == "2";
console.log(x);
x = 2 === 2;
console.log(x);
x = 2 === "2";
console.log(x);
x = 2 != 3;
console.log(x);
x = 2 != "3";
console.log(x);
x = 2 !== 3;
console.log(x);
x = 2 !== "3";
console.log(x);
